name: Pull Request Labeler

on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Label pull request
      if: ${{ github.event.pull_request.head.repo.full_name != 'zhengfeiwang/gh-actions' }}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['fork']
          })
